site_name: Chao World Modding Documentation v2.2.0
site_url: https://nostalgianinja.github.io/ChaoModding_Docs/

nav:
  - Home: index.md
  - Useful pages:
    - Resources: resources.md
    - Examples: examples.md
    - CWE API Code Template: CWEAPICodeTemplate.md
    - Reference - SA2MDL Chao Filenames: RefChaoFiles.md
    - Reference - Chao Data Structure: ChaoDataStruct.md
    - Character Chao using Custom Accessories: CharChaoCustomAccessories.md
    - Checking if CWE Exists: CheckCWE.md
    
  - Tips for beginners:
    - Texturing: beginTexturing.md
    - UV Unwrapping: beginUV.md
    - Code: beginCode.md
    - Testing Mods: TestingMods.md
    - SAIO: beginSAIO.md
    - Asking for help: BeginHelp.md
    
  - Modding Setup:
    - Making a Project: MakingProject.md
    - Setting up your development environment: DevSetup.md
    
  - Creating Mods:
    - Animation Modding: AnimModding.md
    - Fortune Teller Name Mods: FTNaming.md
    - Hat Mods: HatModding.md
    - Fruit Mods: FruitModding.md
    - Accessory Mods: AccessoryModding.md
    - Custom Animal Mods: AnimalModding.md
    - Custom Tree Mods: TreeModding.md
    - Custom Character Chao Mods: CharacterChaoModding.md
    - Lens Mods: LensModding.md   
    
  - Troubleshooting: troubleshooting.md
  
  - Contributing: CONTRIBUTING.md
  
  - Credits: credits.md

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Dark Mode

    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Light Mode

  features:
    - content.code.copy
  logo: logo.png
  favicon: logo.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - md_in_html

plugins:
  - social: 
